nome = str(input("Digite seu nome completo:")).strip()
palavras = (nome.split())
print('{}analisando seu nome...{}'.format('\033[1;30m', '\033[m'))
print('Seu nome em letras maiúsculas é: {}{}{}'.format('\033[1;35m', nome.upper(), '\033[m'))
print('Seu nome em letras minúsculas é: {}{}{}'.format('\033[1;35m', nome.lower(), '\033[m'))
print('Seu nome tem ao todo {}{}{} letras'.format('\033[1;35m', len(nome.replace(" ", "")), '\033[m'))
#                                          ou(len(nome) - nome.count(' '))
print('Seu primeiro nome é {}{}{} e ele tem {}{}{} letras'.format('\033[1;35m', palavras[0], '\033[m', '\033[1;35m', len(palavras[0]), '\033[m'))
#                                                       ou(nome.find(' '))
